version: '3.8'

services:
  web:
    build: .
    ports:
      - "8181:8181"
    environment:
      PORT: 8181
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vldr
    ports:
      - "5432:5432"